rest_encoder_job:
    type: rest
    prefix: /v1
    resource: "Yuav\RestEncoderBundle\Controller\JobController"
    name_prefix:  api_1_ # Avoid naming collision
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc