Yuav\RestEncoderBundle\Entity\Job:
    properties:
        input:
            - NotBlank: ~
            - NotNull: ~
            - Length:
                min: 2
                max: 2048
                minMessage: "Input URI must be at least  characters length"
                maxMessage: "Input URI cannot be longer than  characters length"
Yuav\RestEncoderBundle\Entity\Job2:
    getters:
        input:
            - NotBlank: