yuav_rest_encoder:
    type: rest
    prefix: /api
    resource: "@YuavRestEncoderBundle/Resources/config/routes.yml"
index:
    path:      /
    defaults:  { _controller: YuavRestEncoderBundle:Index:index }
index_request_builder:
    path:      /request_builder
    defaults:  { _controller: YuavRestEncoderBundle:Index:requestBuilder }
file_download:
    path:      /file/{key}
    defaults:  { _controller: YuavRestEncoderBundle:File:download }