yuav_rest_encoder:
    type: rest
    prefix: /api
    resource: "@YuavRestEncoderBundle/Resources/config/routes.yml"
index:
    path:      /
    defaults:  { _controller: YuavRestEncoderBundle:Index:index }
index_request_builder:
    path:      /request_builder
    defaults:  { _controller: YuavRestEncoderBundle:Index:requestBuilder }
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
status:
    path:      /status
    defaults:  { _controller: YuavRestEncoderBundle:Status:index }